image:
  name: acrbd1.azurecr.io/sf:latest
  username: $ACR_USER
  password: $ACR_PASS

clone:
  depth: full

definitions:
  steps:

    - step: &runBlackDuckScan
        name: RunBlackDuckScan
        script:
          - |
              echo "Start of RunBlackDuckScan on ${BITBUCKET_BRANCH}"
              printenv
              chmod 777 ./cicd-scripts/*.sh
              ./cicd-scripts/runBlackDuckScan.sh ${sendPrComment}
              echo "End of RunBlackDuckScan on ${BITBUCKET_BRANCH}"
        after-script:
          - echo "Bitbucket pipeline finished"
        artifacts:
          - '.bridge/**'
        concurrency-group: blackduck-${BITBUCKET_BRANCH}

    - step: &sf-validate
        name: Validation Salesforce
        script:
          - chmod 777 ./cicd-scripts/*.sh
          - ./cicd-scripts/authorizeOrg.sh
          - sf sgd:source:delta --to HEAD --from origin/$BITBUCKET_PR_DESTINATION_BRANCH -i .deltaignore -o .
          - ./cicd-scripts/validateDeployment.sh
          - |
             git fetch origin +refs/heads/$BITBUCKET_PR_DESTINATION_BRANCH:refs/remotes/origin/$BITBUCKET_PR_DESTINATION_BRANCH
             BASE_COMMIT=$(git merge-base HEAD origin/$BITBUCKET_PR_DESTINATION_BRANCH)
             TO_COMMIT=HEAD
             mkdir -p sgd-output
             sf sgd:source:delta --from $BASE_COMMIT --to $TO_COMMIT -o sgd-output --generate-delta
             ls -R sgd-output || true
             if [ -f sgd-output/package/package.xml ]; then
               cp sgd-output/package/package.xml ./package.xml;
             else
               echo "package.xml not found";
             fi
          - if [ -f sgd-output/destructiveChanges/destructiveChanges.xml ]; then
              cp sgd-output/destructiveChanges/destructiveChanges.xml ./destructiveChanges.xml;
            else
              echo "destructiveChanges.xml not found";
            fi
          - cat ./package.xml 
          - cat ./destructiveChanges.xml
          
        artifacts:
          - package.xml
          - destructiveChanges.xml

        concurrency-group: salesforce-validation-${BITBUCKET_BRANCH}

    - step: &sf-deploy
        name: Deploy Salesforce 
        script:
          - chmod 777 ./cicd-scripts/*.sh
          - ./cicd-scripts/authorizeOrg.sh
          - sf sgd:source:delta --to HEAD --from HEAD^ -i .deltaignore -o .
          - ./cicd-scripts/deploySalesforce.sh
        concurrency-group: salesforce-deployment-${BITBUCKET_BRANCH}

    - step: &vlocity-deploy
        name: Deploy Vlocity (Delta)
        script:
          - chmod 777 ./cicd-scripts/*.sh
          - ./cicd-scripts/authorizeOrg.sh
          - ./cicd-scripts/deployVlocityDelta.sh
        concurrency-group: vlocity-deployment-${BITBUCKET_BRANCH}

pipelines:
  pull-requests:
    '{feature/*,Feature/*,FEATURE/*,bugfix/*,Bugfix/*,BUGFIX/*,hotfix/*,Hotfix/*,HOTFIX/*}':
      - parallel:
          - step:
              <<: *runBlackDuckScan
              name: Run Black Duck Scan
          - step:
              <<: *sf-validate
              name: Salesforce Validation
              deployment: SitSF

  branches:
   org/sit:
      - step:
          <<: *sf-deploy
          name: Salesforce Deployment
          deployment: SitSF

      - step:
          <<: *vlocity-deploy
          name: Vlocity Deployment
          deployment: SitVlo

  custom:
    Manual Black Duck Scan:
      - step:
          <<: *runBlackDuckScan
          name: Manual Black Duck Scan
